### ISSUE TITLE
Generated CSS works once, then subsequently fails

### ISSUE THREAD

**Issue by tylershuster** [MozaikAgency/wp-theme-bootstrap#12]
Disclaimer: I'm new to this theme. 

It's working well so far except that after the initial `gulp` command, any further changes to the SCSS cause the theme to break, rendering apparently binary data into the generated main.css. Killing the gulp process and restarting generates a working file.

**Comment by Maximilianos** [comment]
What version of node are you running on?
Does it do this even with just the default files?

**Comment by tylershuster** [comment]
Upgrading Node worked. Thank you!

**Comment by Maximilianos** [comment]
:+1: :smile:

**Comment by tylershuster** [comment]
The same thing is happening again now even with node 0.12.7. There's only a "main.scss" in the complied CSS folder. I'm trying to install another site with the theme as well, and running npm install gives me a long list of `WARN unmet dependency`

**Comment by Maximilianos** [comment]
Can you try a fresh download of the theme, does it do this even with just the default files?

**Comment by tylershuster** [comment]
When I try a fresh download of the theme, it throws two `WARN optional dep failed, continuing fsevents@0.3.8`, then `Killed`. I did `npm rebuild` and it gives me this:

```
> object-fit@0.4.3 postinstall /var/www/tyler/coop/wp-content/themes/coop_dev/node_modules/object-fit
> 


> node-sass@3.3.2 install /var/www/tyler/coop/wp-content/themes/coop_dev/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/tyler/coop/wp-content/themes/coop_dev/node_modules/gulp-sass/node_modules/node-sass/scripts/install.js:6:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.3.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.3.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/tyler/coop/wp-content/themes/coop_dev/npm-debug.log
```

I can send you the file referenced at the end if you'd like.

**Comment by Maximilianos** [comment]
We couldn't replicate your issue on our machines.

It may be any number of things, in the error msg, it says: 

> `npm ERR! This is most likely a problem with the node-sass package`

So you can maybe try posting the issue there as well.

Probably what would work in your case is to `npm install` all the modules that didn't for some reason get automatically installed. Like it says in the error message:

> `Error: Cannot find module 'mkdirp'`

So if you `npm install mkdirp` it should fix this specific error. If it throws a new error for another missing module, follow the same steps until it works.

**Comment by tylershuster** [comment]
This happens intermittently but I'm chalking it up to the server configuration. It doesn't happen when I run everything locally on my Mac. On some remote servers it still happens but it's not greatly inconvenient at this point.
